version: 2.1
jobs:
  build_test:
    docker:
      - image: node:10.19.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Run tests
      - run: npm test

  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command:
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Checking if dirs & build
          command:
            cd ./app && npm install && npm run build
      - run:
          name: Sync with bucket
          command:
            aws s3 sync ./app/build s3://circleci-ci-test-bucket

workflows:
  version: 2
  execute_bulk:
    jobs:
      - build_test
      - build_deploy

