version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-ecr:  circleci/aws-ecr@6.15.3
  aws-ecs:  circleci/aws-ecs@1.4.0

jobs:
  build_test:
    executor:
      name: node/default
      tag: 14.15.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Unit Tests
          command: npm test
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-ouput
      - store_test_results:
          path: /tmp/test-results

  build_deploy:
    docker:
      - image:  circleci/node:10
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip -y
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Checking if dirs & build
          command:
            cd ./app && npm install && npm run build
      - run:
          name: Sync with bucket
          command:
            aws s3 sync ./app/build s3://circleci-ci-test-bucket

workflows:
  execute_bulk:
    jobs:
      - build_test

